    case ('fit_power')
      write(*,*) find_alpha(datatable(1:rownum, xcol_add(1)), rownum, minval(datatable(1:rownum, xcol_add(1))))
    case ('fit_positive_power')
      write(*,*) find_positive_alpha(datatable(1:rownum, xcol_add(1)), rownum, maxval(datatable(1:rownum, xcol_add(1))))
    case ('fit_power_limit')
      write(*,*) find_alpha(datatable(1:rownum, xcol_add(1)), rownum, threshold)
    case ('fit_power_tail')
      call quick_sort(datatable(1:rownum, xcol_add(1)), long_values(1:rownum))
      write(*,*) find_alpha(long_values(3*rownum/4:rownum), rownum/4, minval(long_values(3*rownum/4:rownum)))
